components:
    schemas:
        Bar:
            description:
                Another dummy object to go with Foo.
            properties:
                description:
                    description:
                        Say something about your Bar.
                    type: string
                fooId:
                    description:
                        The associated Foo's ID.
                    format: int64
                    type: integer
                id:
                    description:
                        The Bar's ID
                    format: int64
                    type: integer
                name:
                    description:
                        The title of your Bar.
                    type: string
        Foo:
            description:
                A dummy object that has no meaning.
            properties:
                description:
                    description:
                        Say something about your Foo.
                    type: string
                id:
                    description:
                        The Foo's ID
                    format: int64
                    type: integer
                name:
                    description:
                        The title of your Foo.
                    type: string
            type: object
info:
    description:
        "API to return a Foo."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Foo API"
    version: v1.0
openapi: 3.0.1
paths:
    "/bar/{barId}":
        delete:
            description:
                ""
            operationId: deleteBar
            parameters:
                - in: path
                  name: barId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
                    description:
                        ""
            tags: [ "Bar" ]
        get:
            description:
                ""
            operationId: getBar
            parameters:
                - in: path
                  name: barId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Bar"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Bar"
                    description:
                        "Returns the Bar matching the given product ID."
            tags: [ "Bar" ]
        patch:
            description:
                ""
            operationId: patchBar
            parameters:
                - in: path
                  name: barId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Bar"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Bar"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Bar"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Bar"
                    description:
                        ""
            tags: [ "Bar" ]
        put:
            description:
                ""
            operationId: putBar
            parameters:
                - in: path
                  name: barId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Bar"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Bar"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Bar"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Bar"
                    description:
                        ""
            tags: [ "Bar" ]
    "/foo":
        get:
            description:
                ""
            operationId: getFooPage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
                    description:
                        "Returns the Foo matching the given product ID."
            tags: [ "Foo" ]
        post:
            description:
                ""
            operationId: postFoo
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: ["Foo"]
    "/foo/{fooId}":
        delete:
            description:
                ""
            operationId: deleteFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
                    description:
                        ""
            tags: [ "Foo" ]
        get:
            description:
                ""
            operationId: getFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        "Returns the Foo matching the given product ID."
            tags: ["Foo"]
        patch:
            description:
                ""
            operationId: patchFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: [ "Foo" ]
        put:
            description:
                ""
            operationId: putFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: [ "Foo" ]
    "/foo/{fooId}/bars":
        get:
            description:
                ""
            operationId: getFooBarsPage
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Bar"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Bar"
                                type: array
                    description:
                        "Gets all Bars related to a Foo."
            tags: ["Bar"]
        post:
            description:
                ""
            operationId: postFooBar
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Bar"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Bar"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Bar"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Bar"
                    description:
                        ""
            tags: [ "Bar" ]